In [8]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("spamm.csv")

In [16]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [26]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [28]:
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [49]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [51]:
df.shape

(5572, 3)

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.33, random_state=42)

In [47]:
X_train.shape

(3733,)

In [55]:
X_test.shape

(1839,)

In [59]:
type(X_train)

pandas.core.series.Series

In [61]:
type(X_test)

pandas.core.series.Series

In [63]:
X_train[:4]

3235                                  Yup ü not comin :-(
945     I sent my scores to sophas and i had to do sec...
5319                         Kothi print out marandratha.
5528    Its just the effect of irritation. Just ignore it
Name: Message, dtype: object

In [67]:
y_train[:4]

3235    0
945     0
5319    0
5528    0
Name: spam, dtype: int64

In [71]:
from sklearn.feature_extraction.text import CountVectorizer

v= CountVectorizer()

v.fit_transform(X_train)

<3733x7081 sparse matrix of type '<class 'numpy.int64'>'
	with 49971 stored elements in Compressed Sparse Row format>

In [75]:
X_train_cv = v.fit_transform(X_train)
X_train_cv

<3733x7081 sparse matrix of type '<class 'numpy.int64'>'
	with 49971 stored elements in Compressed Sparse Row format>

In [79]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [81]:
X_train_cv.shape

(3733, 7081)

In [99]:
v.get_feature_names_out()[1000:1050]

array(['asleep', 'asp', 'aspects', 'ass', 'assessment', 'assistance',
       'asssssholeeee', 'assume', 'assumed', 'asthere', 'astne',
       'astrology', 'asus', 'asusual', 'at', 'ate', 'athletic', 'atlanta',
       'atlast', 'atleast', 'atm', 'attach', 'attached', 'attempt',
       'attend', 'attended', 'attraction', 'atural', 'auction',
       'audiitions', 'audition', 'audrey', 'august', 'aunt', 'auntie',
       'aunties', 'aunts', 'aunty', 'aust', 'australia', 'authorise',
       'auto', 'ava', 'availa', 'available', 'avalarr', 'avatar', 'avble',
       'ave', 'avenge'], dtype=object)

In [89]:
v.get_feature_names_out().shape

(7081,)

In [93]:
v.vocabulary_

{'yup': 7068,
 'not': 4414,
 'comin': 1735,
 'sent': 5511,
 'my': 4269,
 'scores': 5442,
 'to': 6329,
 'sophas': 5790,
 'and': 877,
 'had': 3007,
 'do': 2155,
 'secondary': 5467,
 'application': 934,
 'for': 2676,
 'few': 2565,
 'schools': 5436,
 'think': 6246,
 'if': 3279,
 'you': 7047,
 'are': 956,
 'thinking': 6249,
 'of': 4469,
 'applying': 937,
 'research': 5242,
 'on': 4512,
 'cost': 1834,
 'also': 848,
 'contact': 1796,
 'joke': 3500,
 'ogunrinde': 4488,
 'her': 3115,
 'school': 5435,
 'is': 3415,
 'one': 4517,
 'me': 4017,
 'the': 6218,
 'less': 3725,
 'expensive': 2471,
 'ones': 4518,
 'kothi': 3620,
 'print': 4958,
 'out': 4582,
 'marandratha': 3965,
 'its': 3435,
 'just': 3531,
 'effect': 2309,
 'irritation': 3413,
 'ignore': 3282,
 'it': 3427,
 'asked': 995,
 'call': 1453,
 'him': 3132,
 'now': 4425,
 'ok': 4493,
 'whatever': 6827,
 'juliana': 3523,
 'want': 6743,
 'hello': 3102,
 'got': 2925,
 'here': 3116,
 'st': 5880,
 'andrews': 880,
 'boy': 1330,
 'long': 3822,
 'way':

In [137]:
X_train_np = X_train_cv.toarray()
X_train_np[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [127]:
np.where(X_train_np[1]!=0)

(array([ 848,  877,  934,  937,  956, 1796, 1834, 2155, 2471, 2565, 2676,
        3007, 3115, 3279, 3415, 3500, 3725, 4017, 4269, 4469, 4488, 4512,
        4517, 4518, 5242, 5435, 5436, 5442, 5467, 5511, 5790, 6218, 6246,
        6249, 6329, 7047], dtype=int64),)

In [133]:
X_train[945]

'I sent my scores to sophas and i had to do secondary application for a few schools. I think if you are thinking of applying, do a research on cost also. Contact joke ogunrinde, her school is one me the less expensive ones'

In [135]:
v.get_feature_names_out()[848]

'also'

In [139]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)



MultinomialNB()

In [141]:
X_test_cv = v.transform(X_test)

In [143]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99      1593\n           1       0.97      0.95      0.96       246\n\n    accuracy                           0.99      1839\n   macro avg       0.98      0.97      0.98      1839\nweighted avg       0.99      0.99      0.99      1839\n'

In [145]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1593
           1       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



In [153]:
# Testing with an example

Message = [
    'Hey, Mohan. How are you?',
    'Upto 20% discount on parking, Hurry up!'
]

Message_count = v.transform(Message)
model.predict(Message_count)

array([0, 1], dtype=int64)

In [ ]:
df